spring:
  application:
    name: discovery

server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:discoveryService.p12
    key-store-password: ${SERVICE_BOX_KEYSTORE_PASS}
    trust-store: classpath:discoveryService.p12
    trust-store-password: ${SERVICE_BOX_KEYSTORE_PASS}
    key-alias: discovery

security:
  require-ssl: true

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    metadataMap:
      securePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false